const Sequelize = require('sequelize');
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('DatabaseLog', {
    DatabaseLogID: {
      autoIncrement: true,
      type: DataTypes.INTEGER,
      allowNull: false,
      primaryKey: true,
      comment: "Primary key for DatabaseLog re"
    },
    PostTime: {
      type: DataTypes.DATE,
      allowNull: false,
      comment: "Nonclustered index created by "
    },
    DatabaseUser: {
      type: DataTypes.STRING(128),
      allowNull: false,
      comment: "The user who implemented the D"
    },
    Event: {
      type: DataTypes.STRING(128),
      allowNull: false,
      comment: "The type of DDL statement that"
    },
    Schema: {
      type: DataTypes.STRING(128),
      allowNull: true,
      comment: "The schema to which the change"
    },
    Object: {
      type: DataTypes.STRING(128),
      allowNull: true,
      comment: "The object that was changed by"
    },
    TSQL: {
      type: DataTypes.TEXT,
      allowNull: false,
      comment: "The exact Transact-SQL stateme"
    },
    XmlEvent: {
      type: "XML",
      allowNull: false,
      comment: "The raw XML data generated by "
    }
  }, {
    sequelize,
    tableName: 'DatabaseLog',
    schema: 'dbo',
    timestamps: false,
    indexes: [
      {
        name: "PK_DatabaseLog_DatabaseLogID",
        unique: true,
        fields: [
          { name: "DatabaseLogID" },
        ]
      },
    ]
  });
};
